function createfigure_ERP(Y1, Y2)
    %CREATEFIGURE(X1,YMATRIX1)
       X = -499:2:999;
    %  YMATRIX1:  matrix of y data
    
    %  Auto-generated by MATLAB on 08-Feb-2010 22:11:08
    
    % Create figure
    figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);
    
    % Create axes
    axes1 = axes('Parent',figure1,'FontWeight','bold','FontSize',10);
    % Uncomment the following line to preserve the X-limits of the axes
    xlabel(axes1,'Time(㎳)');
    ylabel(axes1,'Amp(㎶)');
    xlim(axes1,[-200 1000]);
    %ylim(axes1,[-25 25]);
    box(axes1,'on');
    hold(axes1,'all');
    
    
    % Create multiple lines using matrix input to plot
    plot1 = plot(X,Y1, 'Parent',axes1,'LineWidth',2);
    hold on;
    plot2 = plot(X,Y2, 'Parent',axes1,'LineWidth',2);
    hold off;
    set(plot1,'LineStyle',':','Color',[1 0 0],'DisplayName','EASY');
    set(plot2,'Color',[0 0 1],'DisplayName','DIFFICULT');
